# Generated by Django 4.2.5 on 2023-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_buyer_offer_admirer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admirer',
            name='funkos',
        ),
        migrations.AddField(
            model_name='funko',
            name='admirers',
            field=models.ManyToManyField(to='main_app.admirer'),
        ),
    ]
